name: build
on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '10.3'
      - name: Build
        run: |
          xcodebuild -workspace "./BSMInputMethod.xcworkspace" -scheme "BSMInputMethod" -configuration "Release"
